#!/bin/bash

WHOAMI=$(whoami)
if [ "$WHOAMI" != "root" ]; then
  echo "Must be root"
  exit 1
fi

while [ 1 -lt 2 ]; do
  echo ""
  echo "Risk (low)"
  PIDS=$(ps aux | grep RISK | tr -s ' ' ' ' | cut -d ' ' -f2)
  for f in $(echo $PIDS); do
    echo "Found [$f]"
    renice 10 $f
  done

  echo ""
  echo "Steam (low)"
  PIDS=$(ps aux | grep -i steam | tr -s ' ' ' ' | cut -d ' ' -f2)
  for f in $(echo $PIDS); do
    echo "Found [$f]"
    renice 10 $f
  done

  echo ""
  echo "Hearthstone (low)"
  PIDS=$(ps aux | grep -i hearthstone | tr -s ' ' ' ' | cut -d ' ' -f2)
  for f in $(echo $PIDS); do
    echo "Found [$f]"
    renice 10 $f
  done

  echo ""
  echo "Battlenet"
  PIDS=$(ps aux | grep Battle | tr -s ' ' ' ' | cut -d ' ' -f2)
  for f in $(echo $PIDS); do
    echo "Found [$f]"
    renice 10 $f
  done

  echo ""
  echo "synergy (high)"
  PIDS=$(ps aux | grep -i synergy | tr -s ' ' ' ' | cut -d ' ' -f2)
  for f in $(echo $PIDS); do
    echo "Found [$f]"
    renice -2 $f
  done

  sleep 30
done
